### ISSUE TITLE
product variation is not working in the second language

### ISSUE THREAD

**Issue by vonsch76** [qTranslate-Team/qtranslate-x#78]
Installed the new version (3.2.7) and (woocommerce) product variation is not working on the second language, shows only an empty selector box. The first language works well, though. The previous version (3.2.2) was working in both languages. Have only 2 languages on the page, so guess the issue is the same with 3 or more languages.

**Comment by johnclause** [comment]
Hi @vonsch76: could you test the latest integration plugin [WooCommerce & qTranslate-X](https://github.com/qTranslate-Team/woocommerce-qtranslate-x) from GitHub?

You can also update and test [qTranslate-X](https://github.com/qTranslate-Team/qtranslate-x) from GitHub, since it has many new additions, but it should not be matter for this particular problem.

**Comment by vonsch76** [comment]
John, I did, but unfortunately there is no success, the result is the same.
The code is running in a staging environment at the moment, that uses a
copy of the data from the real site.

the orignal product - Hungarian
http://testenv.hajoznijo.hu/termek/hot-punch-cruising/

translation - English
http://testenv.hajoznijo.hu/en/termek/hot-punch-cruising/

I am happy to provide access to the team if you wish to investigate.

**Comment by vonsch76** [comment]
Will give it a second try, see that you had commit 4 hours ago, I tried the
version last evening, so about 10 hours ago.

**Comment by vonsch76** [comment]
Installed the latest, no change. You can check yourself on the links
provided earlier. The language is dummy, but the product is an existing one
and works on the main language.

**Comment by johnclause** [comment]
Just to confirm, you installed the latest versions for **both** plugins:  [WooCommerce & qTranslate-X](https://github.com/qTranslate-Team/woocommerce-qtranslate-x) and  [qTranslate-X](https://github.com/qTranslate-Team/qtranslate-x), is that correct?

**Comment by johnclause** [comment]
If so, then, yes I am ready to get an access to your installation. Actually, one more thing to try, could you re-save attributes in trouble, just press applicable "Save" buttons one more time and see if it changes anything.

**Comment by vonsch76** [comment]
John, Tried to resave the attributes, unfortunately that is not the
problem.

The reply to your questions is yes for both. Used the latest Qtranslate-x
from github and stock Woocommerce & qTranslate-X from the Wordpress
Plugins. Don't know if anything has changed from the last version, but for
sure that not Woocommerce and qTranslate-X is the problem. When I changed
back to the old version (3.2.2), then attributes are displayed on all
languages.

Please send me a mail, so I can provide you admin. My address is
kornel.schwarcz at gmail.

**Comment by johnclause** [comment]
>stock Woocommerce & qTranslate-X

Please, take  [WooCommerce & qTranslate-X](https://github.com/qTranslate-Team/woocommerce-qtranslate-x) from GitHub too. The link points to GitHub. Sorry for the confusion.

**Comment by vonsch76** [comment]
Thanks, seems that the issue is solved. All options are displayed correct.

**Comment by johnclause** [comment]
:+1:

**Comment by Samverylazy** [comment]
@vonsch76  Hi, How did you solve this problem finally ? I meet this trouble in the latest version of woocommerce and qtranslate-X. Product data not switched while switch language tab. 

Thanks

**Comment by vonsch76** [comment]
Updated to WordPress 4.2.2 and seems that the issue is solved.

**Comment by garukb1** [comment]
Hi guys, I have the exact same problem in second language it shows empty selector box. I just updated everything ( WooCommerce & qTranslate-X, qTranslate-X, woocomerce, Wordpress core) but the problem still remains. I have 3 languages VN, FR, EN but only FR  got the problem? Do you guys have any ideal since you solved last time. Thank you very much

**Comment by vonsch76** [comment]
I stayed at WP 4.2.2, reliability is more important, then fancy operation for me. Sometimes the second language content disappear, so there is something, but other than that, it works fine. You may also want to check whether you have enough resources on the server - wrong host, overloaded server caused weird errors on my site.
